### PR TITLE
Css generator

### PR DESCRIPTION
**Pull request by kenlog**
I closed the old branch now obsolete. Let's start a new path from here

### CODE REVIEW

**Comment by kenlog** [comment]
great @creecros ! I immediately go to work :construction_worker:

**Comment by kenlog** [comment]
@creecros We will also have to include a selection to load an existing theme and make changes. It would take us what do you think?

**Comment by creecros** [comment]
Yes, that will be the "Modify a Theme" feature.  We could incorporate into the "Create Theme" accordion section, or have it's own accordion titled "Modify Themes" 

I was thinking we should separate the two, and call a different function inside the controller for it, since it will function differently, and that way we can finish the "Create Theme" function, and then move on to the "Modify Theme" portion.

**Comment by creecros** [comment]
once we finish them both, we could move them into the "Manage Themes" accordion as Tabs.

**Comment by kenlog** [comment]
I thought something similar, for me it's okay. For the moment I started to include a few classes for the creator :art:, later I push everything on the branch.

**Comment by creecros** [comment]
we might want some type of memory on that accordion. when you enable the login page settings, i think we should come back to the page with that accordion open.

**Comment by kenlog** [comment]
you're right, I think it can be done.

**Comment by creecros** [comment]
I figured out the live preview, I'll work on that. If we still want the memory, just send a value to the configmodel, like 1-4, and open the accordian based on the value.

**Comment by creecros** [comment]
unless, of course, you have a better solution.

**Comment by creecros** [comment]
apparently, the live preview is trivial. You may want to take a look as well.

onchange does not work.
oninput will work, but only if you type in the color textarea, not after choosing from the picker.

it's the color picker that's causing the issue.

**Comment by creecros** [comment]
figured it out, it's gonna take me a bit to completely update it

**Comment by creecros** [comment]
image

was thinking on this, and maybe to reduce options, invert the colors on the hovers, like the login button.

**Comment by kenlog** [comment]
@creecros Beautiful the latest version!:tada: As soon as I can, I will add more classes for style, promised.

**Pull request merged**
