### PR TITLE
added basic transparency to the panel is removed heavy shadow

### PR DESCRIPTION
**Pull request by kenlog**
Hi @creecros, I have made improvements to the access panel, I hope you like them.
As long as the user does not decide to change the color of the panel will remain transparent, this in my opinion is better suited to any background.

### CODE REVIEW

**Comment by creecros** [comment]
take a look at these:
https://github.com/bgrins/spectrum
https://github.com/farbelous/bootstrap-colorpicker

**Comment by creecros** [comment]
this one was super easy.
http://www.menucool.com/rgba-color-picker

**Comment by creecros** [comment]
I can look at the shadow tomorrow, if you don't have the time.

**Comment by creecros** [comment]
also, I changed the paths for a few things so the weren't absolute

**Comment by kenlog** [comment]
Hi @creecros! I find this implementation simply fantastic, I really like it! I agree with you this way and in line with the plugin title. :1st_place_medal:

**Comment by creecros** [comment]
Lots of fun options now!

**Pull request merged**
