### PR TITLE
NEW: Styling Changes

### LINKED ISSUE #3: No CSS file?
Is there no way to customise the css of the plugin?

For the KanboardCSS theme plugin, this works:
```
.logo > a > img {vertical-align:middle;} /* This aligns the logo certically to the text */
.form-login > a > img {display: block;margin: auto;} /* This makes the logo centralised */
```

### PR DESCRIPTION
**Pull request by aljawaid**
- Style login form on login page
- Fixes #3
- Styled plugin settings page for better user experience
- Add more css classes for specific styling
- FIX: Title in page header to support consistency
- NEW: Titles per section in plugin settings
- NEW: Colour-coded file upload/remove icons for better user experience

### CODE REVIEW

**Comment by creecros** [comment]
I'll merge when github goes green, been having issues all day.
https://status.github.com/messages

**Comment by creecros** [comment]
I modified the shadow a bit, toned it down, hope you don't mind.

Also, worth noting, Nebula login is no longer having theme colors applied correctly. Is there a way to at least maintain the blue background and not override to white?

@kenlog @aljawaid 

image

**Comment by aljawaid** [comment]
> I modified the shadow a bit, toned it down, hope you don't mind.
- No issues on the background shadow, I made it that way due to random colourful unsplash images.

> Also, worth noting, Nebula login is no longer having theme colors applied correctly. Is there a way to at least maintain the blue background and not override to white?
- White background was to prevent unsplash images on confusing/covering the login text.  The only solution would be if you create a setting for with and without:
 - With unsplash setting: white background
 - Without unsplash setting: no login background

I can do the css part if you can create the setting.  I think if you create a setting `without unsplash` then we can apply the `without-unsplash` class to the `form-login` - then I can style it.

Likewise if you create a setting `with-unsplash` then we can apply the `with-unsplash` class to the `form-login` - then I can style that too.

Alternatively, you could create a checkbox type setting to `apply white background` which would activate the css class `white-background` to `form-login` then I will MOVE the background colour from the current way to the `white-backgroud` class.

If you let me know which setting method you use/change, I can sort the css out tonight.

These two settings should solve the nebula issue I think.

**Comment by creecros** [comment]
There already is a unsplash setting, aka background URL, $customizer['backURL']. `isset($customizer['backURL'])` should return false if it is not set.

I might not need it though, added a color picker for login background color.

**Comment by creecros** [comment]
actually, playing with this, we could provide the settings for a custom theme color scheme. The css would have to be in a php file, probably attached to layout.php.

**Comment by creecros** [comment]
yeah, works....could do this for everything and give users ability to create their own color scheme:

image

image

**Comment by aljawaid** [comment]
That's great, but if you choose unsplash as url or enter url then the background page colour will be ignored right?

**Comment by creecros** [comment]
correct, you won't see it. If you don't use a background image link, you will see it.

**Pull request merged**
